### ISSUE TITLE
Include GO Root Node Selection in ErmineJ.CLI

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/ermineJ#2]
While it is possible to subset the GO Tree by its root node in the GUI (biological process, molecular function, cellular location), the option to perform subsetting in the CLI is not obvious (all three are used by default), resulting in incorrect FDR estimates if subsetting was intended.

Potential workaround is to use a customized config file via "--config (-C)", though whether to have optional flags may be a consideration.

**Comment by ppavlidis** [comment]
I'm adding an option like --aspect {BCM}
So you chose B for BP
C for CC
M for MF
Or any combination. OK?

**Comment by nzllim** [comment]
Sounds like a good ~compromise~ implementation. Testing using 3.0.4-Snapshot and "Biological Process only" appears to replicate previous results.

**Comment by ppavlidis** [comment]
I'm not sure why it is a compromise - what would be ideal?

**Comment by nzllim** [comment]
Oh, what I had in mind was separate "single dash" flags for that end, though I think this current implementation (--aspect) is much better since it is less messy both for the developer and user.
(tl;dr: Wrong choice of words...)
