### ISSUE TITLE
Saveconfig (-S) flag in ErmineJ.CLI does not appear to work

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/ermineJ#3]
As title, configuration file is not created as indicated.

**Comment by ppavlidis** [comment]
Error message or just silently fails to do so?

**Comment by nzllim** [comment]
Silently fails to do so. It should be noted that the flag was used in conjunction with an analysis (i.e. analysis relevant flags were raised).

**Comment by ppavlidis** [comment]
I committed a simple fix but yet to test.

**Comment by nzllim** [comment]
3.0.4-Snapshot appears to fix the problem.
